apiVersion: v1
kind: Service
metadata:
  name: blog-devops-service
  namespace: blog-prod
  labels:
    app: blog-devops
    env: prod
spec:
  selector:
    app: blog-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
