apiVersion: v1
kind: Service
metadata:
  name: vibe-devops-prod-service
  namespace: vibe-prod
spec:
  selector:
    app: vibe-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
