all:
  children:
    k3s_cluster:
      children:
        masters:
          hosts:
            k3s-master-0:
              ansible_host: 10.0.20.21
            k3s-master-1:
              ansible_host: 10.0.20.22
            k3s-master-2:
              ansible_host: 10.0.20.23
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/kompot/.ssh/id_ed25519 
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'